# influx 1.2
influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
  environment:
    - INFLUXDB_ADMIN_ENABLED=true
  volumes:
    - ./DOCKER_DATA/influxdb:/var/lib/influxdb
